/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserSettingsDto"];
                        "application/json": components["schemas"]["UserSettingsDto"];
                        "text/json": components["schemas"]["UserSettingsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserSettingsDto"];
                    "text/json": components["schemas"]["UserSettingsDto"];
                    "application/*+json": components["schemas"]["UserSettingsDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserSettingsDto"];
                        "application/json": components["schemas"]["UserSettingsDto"];
                        "text/json": components["schemas"]["UserSettingsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    listId?: string[];
                    archived?: boolean;
                    trashed?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NoteDto"][];
                        "application/json": components["schemas"]["NoteDto"][];
                        "text/json": components["schemas"]["NoteDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNoteDto"];
                    "text/json": components["schemas"]["CreateNoteDto"];
                    "application/*+json": components["schemas"]["CreateNoteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NoteDto"];
                        "application/json": components["schemas"]["NoteDto"];
                        "text/json": components["schemas"]["NoteDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NoteDto"];
                        "application/json": components["schemas"]["NoteDto"];
                        "text/json": components["schemas"]["NoteDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNoteDto"];
                    "text/json": components["schemas"]["UpdateNoteDto"];
                    "application/*+json": components["schemas"]["UpdateNoteDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NoteDto"];
                        "application/json": components["schemas"]["NoteDto"];
                        "text/json": components["schemas"]["NoteDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NoteStateDto"];
                    "text/json": components["schemas"]["NoteStateDto"];
                    "application/*+json": components["schemas"]["NoteStateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NoteDto"];
                        "application/json": components["schemas"]["NoteDto"];
                        "text/json": components["schemas"]["NoteDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/notes/{id}/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetNoteListsDto"];
                    "text/json": components["schemas"]["SetNoteListsDto"];
                    "application/*+json": components["schemas"]["SetNoteListsDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NoteDto"];
                        "application/json": components["schemas"]["NoteDto"];
                        "text/json": components["schemas"]["NoteDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListDto"][];
                        "application/json": components["schemas"]["ListDto"][];
                        "text/json": components["schemas"]["ListDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateListDto"];
                    "text/json": components["schemas"]["CreateListDto"];
                    "application/*+json": components["schemas"]["CreateListDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListDto"];
                        "application/json": components["schemas"]["ListDto"];
                        "text/json": components["schemas"]["ListDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateListDto"];
                    "text/json": components["schemas"]["UpdateListDto"];
                    "application/*+json": components["schemas"]["UpdateListDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ListDto"];
                        "application/json": components["schemas"]["ListDto"];
                        "text/json": components["schemas"]["ListDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequestDto"];
                    "text/json": components["schemas"]["RegisterRequestDto"];
                    "application/*+json": components["schemas"]["RegisterRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/changepassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequestDto"];
                    "text/json": components["schemas"]["ChangePasswordRequestDto"];
                    "application/*+json": components["schemas"]["ChangePasswordRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                    "text/json": components["schemas"]["LoginRequestDto"];
                    "application/*+json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponseDto: {
            accessToken?: string;
            /** Format: date-time */
            accessTokenExpiresAtUtc?: string;
            user?: components["schemas"]["UserDto"];
        };
        ChangePasswordRequestDto: {
            userId?: string;
            newPassword: string;
            currentPassword?: string;
        };
        ChecklistItemDto: {
            /** Format: uuid */
            id?: null | string;
            text?: string;
            isChecked?: boolean;
            /** Format: int32 */
            order?: number;
        };
        CreateListDto: {
            name: string;
            color?: null | string;
        };
        CreateNoteDto: {
            type?: components["schemas"]["NoteType"];
            title?: null | string;
            body?: null | string;
            color?: null | string;
            checklistItems?: null | components["schemas"]["ChecklistItemDto"][];
            listIds?: null | string[];
        };
        ListDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            color?: null | string;
            /** Format: int32 */
            noteCount?: number;
            /** Format: date-time */
            createdAtUtc?: string;
        };
        LoginRequestDto: {
            email: string;
            password: string;
        };
        NoteDto: {
            /** Format: uuid */
            id?: string;
            type?: components["schemas"]["NoteType"];
            title?: null | string;
            body?: null | string;
            color?: null | string;
            isPinned?: boolean;
            isArchived?: boolean;
            isTrashed?: boolean;
            /** Format: date-time */
            createdAtUtc?: string;
            /** Format: date-time */
            updatedAtUtc?: string;
            checklistItems?: components["schemas"]["ChecklistItemDto"][];
            listIds?: string[];
        };
        NoteStateDto: {
            isPinned?: null | boolean;
            isArchived?: null | boolean;
            isTrashed?: null | boolean;
        };
        /** @enum {unknown} */
        NoteType: "Text" | "Checklist" | "Image";
        RegisterRequestDto: {
            email: string;
            password: string;
            displayName?: null | string;
        };
        SetNoteListsDto: {
            listIds?: string[];
        };
        UpdateListDto: {
            name?: null | string;
            color?: null | string;
        };
        UpdateNoteDto: {
            type?: components["schemas"]["NoteType"];
            title?: null | string;
            body?: null | string;
            color?: null | string;
            checklistItems?: null | components["schemas"]["ChecklistItemDto"][];
        };
        UserDto: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: null | string;
        };
        UserSettingsDto: {
            /** Format: uuid */
            id?: null | string;
            globalAccentColor?: string;
            theme?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
