/**
 * The keepIT app icon — the rendered typewriter, the same picture as the favicon and the Android
 * launcher. `public/keepit-icon.png` is generated by `docs/brand/render_icons.py` from
 * `docs/brand/keepit-icon.blend`; edit the .blend, never the PNG. Decorative: it always sits next
 * to the "keepIT" wordmark, which is what a screen reader should announce.
 */
export function BrandMark({ className }: { className?: string }) {
  return <img src="/keepit-icon.png" alt="" draggable={false} className={className} />;
}
